export const productsData = [
  //"products": [
    {
      "id": 1,
      "title": "Digital Camera",
      "description": "This is a dummy description for digital camera.",
      "price": 114.32,
      "discountPercentage": 9.09,
      "rating": 4.96,
      "stock": 77,
      "brand": "KitchenKing",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Digital+Camera",
      "image": "https://dummyimage.com/600x600/000/fff&text=Digital+Camera"
    },
    {
      "id": 2,
      "title": "Leather Wallet",
      "description": "This is a dummy description for leather wallet.",
      "price": 47.97,
      "discountPercentage": 23.42,
      "rating": 4.79,
      "stock": 122,
      "brand": "StyleCo",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Leather+Wallet",
      "image": "https://dummyimage.com/600x600/000/fff&text=Leather+Wallet"
    },
    {
      "id": 3,
      "title": "Desk Lamp",
      "description": "This is a dummy description for desk lamp.",
      "price": 166.87,
      "discountPercentage": 13.09,
      "rating": 3.5,
      "stock": 42,
      "brand": "TechZone",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Desk+Lamp",
      "image": "https://dummyimage.com/600x600/000/fff&text=Desk+Lamp"
    },
    {
      "id": 4,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 92.28,
      "discountPercentage": 6.55,
      "rating": 4.12,
      "stock": 13,
      "brand": "KitchenKing",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 5,
      "title": "Yoga Mat",
      "description": "This is a dummy description for yoga mat.",
      "price": 340.86,
      "discountPercentage": 5.64,
      "rating": 3.83,
      "stock": 30,
      "brand": "KitchenKing",
      "category": "fashion",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Yoga+Mat",
      "image": "https://dummyimage.com/600x600/000/fff&text=Yoga+Mat"
    },
    {
      "id": 6,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 493.52,
      "discountPercentage": 28.58,
      "rating": 3.82,
      "stock": 57,
      "brand": "FitPro",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 7,
      "title": "LED Monitor",
      "description": "This is a dummy description for led monitor.",
      "price": 24.48,
      "discountPercentage": 6.41,
      "rating": 4.84,
      "stock": 148,
      "brand": "TrendyGear",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=LED+Monitor",
      "image": "https://dummyimage.com/600x600/000/fff&text=LED+Monitor"
    },
    {
      "id": 8,
      "title": "Phone Case",
      "description": "This is a dummy description for phone case.",
      "price": 106.18,
      "discountPercentage": 9.09,
      "rating": 4.27,
      "stock": 50,
      "brand": "StyleCo",
      "category": "kitchen",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Phone+Case",
      "image": "https://dummyimage.com/600x600/000/fff&text=Phone+Case"
    },
    {
      "id": 9,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 93.05,
      "discountPercentage": 21.25,
      "rating": 4.38,
      "stock": 112,
      "brand": "StyleCo",
      "category": "kitchen",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 10,
      "title": "Phone Case",
      "description": "This is a dummy description for phone case.",
      "price": 193.26,
      "discountPercentage": 27.21,
      "rating": 3.75,
      "stock": 110,
      "brand": "StyleCo",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Phone+Case",
      "image": "https://dummyimage.com/600x600/000/fff&text=Phone+Case"
    },
    {
      "id": 11,
      "title": "Espresso Machine",
      "description": "This is a dummy description for espresso machine.",
      "price": 368.83,
      "discountPercentage": 15.07,
      "rating": 3.61,
      "stock": 179,
      "brand": "KitchenKing",
      "category": "fashion",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Espresso+Machine",
      "image": "https://dummyimage.com/600x600/000/fff&text=Espresso+Machine"
    },
    {
      "id": 12,
      "title": "Sunglasses",
      "description": "This is a dummy description for sunglasses.",
      "price": 411.18,
      "discountPercentage": 7.91,
      "rating": 4.87,
      "stock": 69,
      "brand": "HomeEssentials",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Sunglasses",
      "image": "https://dummyimage.com/600x600/000/fff&text=Sunglasses"
    },
    {
      "id": 13,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 491.98,
      "discountPercentage": 13.49,
      "rating": 3.62,
      "stock": 91,
      "brand": "KitchenKing",
      "category": "home",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 14,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 432.55,
      "discountPercentage": 19.91,
      "rating": 4.45,
      "stock": 126,
      "brand": "FitPro",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 15,
      "title": "Wireless Mouse",
      "description": "This is a dummy description for wireless mouse.",
      "price": 345.26,
      "discountPercentage": 22.81,
      "rating": 4.14,
      "stock": 160,
      "brand": "HomeEssentials",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Wireless+Mouse",
      "image": "https://dummyimage.com/600x600/000/fff&text=Wireless+Mouse"
    },
    {
      "id": 16,
      "title": "Fitness Tracker",
      "description": "This is a dummy description for fitness tracker.",
      "price": 417.44,
      "discountPercentage": 12.06,
      "rating": 4.62,
      "stock": 136,
      "brand": "FitPro",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Fitness+Tracker",
      "image": "https://dummyimage.com/600x600/000/fff&text=Fitness+Tracker"
    },
    {
      "id": 17,
      "title": "Running Shoes",
      "description": "This is a dummy description for running shoes.",
      "price": 194.86,
      "discountPercentage": 12.72,
      "rating": 3.9,
      "stock": 179,
      "brand": "HomeEssentials",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Running+Shoes",
      "image": "https://dummyimage.com/600x600/000/fff&text=Running+Shoes"
    },
    {
      "id": 18,
      "title": "Digital Camera",
      "description": "This is a dummy description for digital camera.",
      "price": 310.3,
      "discountPercentage": 14.95,
      "rating": 4.34,
      "stock": 61,
      "brand": "TechZone",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Digital+Camera",
      "image": "https://dummyimage.com/600x600/000/fff&text=Digital+Camera"
    },
    {
      "id": 19,
      "title": "Digital Camera",
      "description": "This is a dummy description for digital camera.",
      "price": 300.45,
      "discountPercentage": 15.76,
      "rating": 4.96,
      "stock": 60,
      "brand": "HomeEssentials",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Digital+Camera",
      "image": "https://dummyimage.com/600x600/000/fff&text=Digital+Camera"
    },
    {
      "id": 20,
      "title": "Desk Lamp",
      "description": "This is a dummy description for desk lamp.",
      "price": 227.75,
      "discountPercentage": 9.09,
      "rating": 4.28,
      "stock": 49,
      "brand": "HomeEssentials",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Desk+Lamp",
      "image": "https://dummyimage.com/600x600/000/fff&text=Desk+Lamp"
    },
    {
      "id": 21,
      "title": "Backpack",
      "description": "This is a dummy description for backpack.",
      "price": 253.26,
      "discountPercentage": 14.1,
      "rating": 4.8,
      "stock": 61,
      "brand": "TechZone",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Backpack",
      "image": "https://dummyimage.com/600x600/000/fff&text=Backpack"
    },
    {
      "id": 22,
      "title": "Yoga Mat",
      "description": "This is a dummy description for yoga mat.",
      "price": 397.26,
      "discountPercentage": 19.42,
      "rating": 3.7,
      "stock": 43,
      "brand": "TrendyGear",
      "category": "fitness",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Yoga+Mat",
      "image": "https://dummyimage.com/600x600/000/fff&text=Yoga+Mat"
    },
    {
      "id": 23,
      "title": "Gaming Keyboard",
      "description": "This is a dummy description for gaming keyboard.",
      "price": 457.79,
      "discountPercentage": 29.52,
      "rating": 4.21,
      "stock": 35,
      "brand": "HomeEssentials",
      "category": "fashion",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Gaming+Keyboard",
      "image": "https://dummyimage.com/600x600/000/fff&text=Gaming+Keyboard"
    },
    {
      "id": 24,
      "title": "Phone Case",
      "description": "This is a dummy description for phone case.",
      "price": 298.74,
      "discountPercentage": 15.49,
      "rating": 4.44,
      "stock": 21,
      "brand": "KitchenKing",
      "category": "kitchen",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Phone+Case",
      "image": "https://dummyimage.com/600x600/000/fff&text=Phone+Case"
    },
    {
      "id": 25,
      "title": "Bluetooth Headphones",
      "description": "This is a dummy description for bluetooth headphones.",
      "price": 429.3,
      "discountPercentage": 19.48,
      "rating": 4.3,
      "stock": 191,
      "brand": "TrendyGear",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Bluetooth+Headphones",
      "image": "https://dummyimage.com/600x600/000/fff&text=Bluetooth+Headphones"
    },
    {
      "id": 26,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 255.99,
      "discountPercentage": 15.43,
      "rating": 4.98,
      "stock": 143,
      "brand": "StyleCo",
      "category": "accessories",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 27,
      "title": "Yoga Mat",
      "description": "This is a dummy description for yoga mat.",
      "price": 337.81,
      "discountPercentage": 10.64,
      "rating": 3.79,
      "stock": 155,
      "brand": "FitPro",
      "category": "home",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Yoga+Mat",
      "image": "https://dummyimage.com/600x600/000/fff&text=Yoga+Mat"
    },
    {
      "id": 28,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 203.97,
      "discountPercentage": 29.11,
      "rating": 4.08,
      "stock": 25,
      "brand": "TrendyGear",
      "category": "kitchen",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 29,
      "title": "Water Bottle",
      "description": "This is a dummy description for water bottle.",
      "price": 374.07,
      "discountPercentage": 12.9,
      "rating": 3.94,
      "stock": 135,
      "brand": "TrendyGear",
      "category": "electronics",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Water+Bottle",
      "image": "https://dummyimage.com/600x600/000/fff&text=Water+Bottle"
    },
    {
      "id": 30,
      "title": "Smartwatch",
      "description": "This is a dummy description for smartwatch.",
      "price": 166.28,
      "discountPercentage": 17.09,
      "rating": 3.61,
      "stock": 199,
      "brand": "FitPro",
      "category": "kitchen",
      "thumbnail": "https://dummyimage.com/300x300/000/fff&text=Smartwatch",
      "image": "https://dummyimage.com/600x600/000/fff&text=Smartwatch"
    },
  //],
   
  // "total": 30,
  // "skip": 0,
  // "limit": 30
]  
  //};